tasks:
  - init: npm install -g typescript nodemon yarn
    command: npm globals

ports:
  - port: 3000

vscode:
  extensions:
    - octref.vetur@0.24.0:wQwUWmMBrV2Y+ZN1GPaapg==
    - chenxsan.vscode-standardjs@1.2.3:2t/tdtP+Oe0FOyAxtlmquA==