const CONSTANTS = {}
CONSTANTS.COSMOS = {}
CONSTANTS.ENDPOINT = {}

CONSTANTS.PORT = process.env.PORT || '3000'
CONSTANTS.ENDPOINT.MASTERDETAIL = '/masterdetail'

CONSTANTS.ENDPOINT.LIST = '/list'

CONSTANTS.ENDPOINT.GRID = '/grid'

CONSTANTS.COSMOS.COLLECTION = 'ListItems'
module.exports = CONSTANTS
